service: stripe-webhook

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

functions:
  webhook:
    handler: lambda-webhook.handler
    events:
      - http:
          path: webhook
          method: post
          cors: true
    timeout: 30
    memorySize: 256

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
